Add `http` or `https` local run

diff --git a/deploy/Dockerfile b/deploy/Dockerfile
--- a/deploy/Dockerfile
+++ b/deploy/Dockerfile
@@ -13,9 +13,17 @@ FROM caddy:2.6.4-alpine as run
 
 WORKDIR /droneDOCS
 COPY --from=build /code/droneDOCS/docs/.vitepress/dist .
-# TODO: ARG https or not
-COPY deploy/Caddyfile-https /etc/caddy/Caddyfile
-EXPOSE 80
+COPY deploy/Caddyfile-* /etc/caddy/
+
+ARG HTTP_OR_HTTPS=http
+# Check if passed ONLY 'http' or 'https'
+RUN ([[ "$HTTP_OR_HTTPS" != "http" ]] && [[ "$HTTP_OR_HTTPS" != "https" ]] && echo "ERROR - Set HTTP_OR_HTTPS to 'http' or 'https'" && exit 1) || \
+# Check if passed 'http'
+  ([[ "$HTTP_OR_HTTPS" == "http" ]] && rm -f /etc/caddy/Caddyfile-https && mv /etc/caddy/Caddyfile-http /etc/caddy/Caddyfile) || \
+# Check if passed 'https'
+  ([[ "$HTTP_OR_HTTPS" == "https" ]] && rm -f /etc/caddy/Caddyfile-http && mv /etc/caddy/Caddyfile-https /etc/caddy/Caddyfile)
+
+EXPOSE 80 443
 
 RUN adduser -h /droneDOCS -s /bin/ash -D -u 2000 caddy && \
   chown -R caddy:caddy /droneDOCS /data/caddy
